version: "3"

services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  test:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    command: mix do deps.get --only, coveralls --trace --color
    environment:
      - MIX_ENV=test
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=questions_test
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5403:5432"
    networks:
      default:
        aliases:
          - questions-db